# Generated by Django 4.1.5 on 2023-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorite",
            old_name="recipie",
            new_name="recipe",
        ),
    ]
