@host = http://localhost:8000

@token = Token 0da6072bdd81e0527578f8b5e86214d9aa59e1f7

@user_token = Token 5e40f8dbac5b7c643db1bf4b2b694566ebede581

### list of tags

GET {{ host }}/api/tags/ HTTP/1.1
content-type: application/json

### add tags

POST {{ host }}/api/tags/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}


{
  "name": "somefast",
  "color": "#234232",
  "slug": "smfstoauouoaeuaeuuaouoa"
}


### tag detail

GET {{ host }}/api/tags/2/ HTTP/1.1
content-type: application/json


# INGREDIENTS


### list of ingredients

GET {{ host }}/api/ingredients/?search=аво HTTP/1.1
content-type: application/json

### ingredient detail

GET {{ host }}/api/ingredients/279/ HTTP/1.1
content-type: application/json

# USERS

### get/detail users

GET {{host}}/api/users/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### subscribe
POST  {{ host }}/api/users/2/subscribe/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### desubscribe

DELETE {{ host }}/api/users/2/subscribe/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### subscriptions    http://localhost/api/users/subscriptions/
GET {{ host }}/api/users/subscriptions/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### get me

GET {{host}}/api/users/me/ HTTP/1.1
content-type: application/json
Authorization: {{ user_token }}

### reg new user

POST {{host}}/api/users/ HTTP/1.1
content-type: application/json

{
  "email": "mail@oru.ru",
  "username": "anatol2",
  "first_name": "Tolic",
  "last_name": "Levchenko",
  "password": "automata5"  
}

### change password

POST {{host}}/api/users/set_password/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

{
    "new_password": "automata",
    "current_password": "automata2"
}
### user login
POST {{host}}/api/auth/token/login/ HTTP/1.1
content-type: application/json

{
    "email": "mail@oru.ru",
    "password": "automata5"
}
### user logout
POST {{host}}/api/auth/token/logout/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

###


# RECIPES


### recipes list/detail

GET {{ host }}/api/recipes/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}


### recipes shopping_cart

POST {{ host }}/api/recipes/2/shopping_cart/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### recipes favorite

POST {{ host }}/api/recipes/1/favorite/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### cart download

GET {{ host }}/api/recipes/download_shopping_cart/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

### recipes del

DELETE {{ host }}/api/recipes/7/ HTTP/1.1
content-type: application/json

### recipes post as in redoc:

POST  {{ host }}/api/recipes/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

{
    "name": "snack",
    "tags": [4],
    "text": "boiled meat pies",
    "cooking_time": 190,
    "ingredients": [
      {
        "id": 1800,
        "amount": 7
      },
      {
        "id": 6,
        "amount": 1
      },
      {
        "id": 2000,
        "amount": 4
      }

    ]
}

###

PATCH  {{ host }}/api/recipes/3/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

{   
    "author": 2,
    "cooking_time": 7,
    "ingredients": [      {
        "id": 605,
        "amount": 1
      },
      {
        "id": 209,
        "amount": 4
      }],
    "tags": [2]
}

###











###
POST {{host}}users/set_password/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

{ 
  "new_password": "it_works",
  "current_password": "it_works_again"
}
###

###
POST {{host}}auth/token/logout/ HTTP/1.1
content-type: application/json
Authorization: {{ token }}

{
  "username": "maria",
  "password": "t3DwwT#hnh8"
}

###
POST {{host}}auth/users/ HTTP/1.1
content-type: application/json

{
  "username": "maria",
  "password": "t3DwwT#hnh8",
  "email": "some@mail.gav"
}
###

POST {{host}}auth/token/login/ HTTP/1.1
content-type: application/json

{
  "username": "maria",
  "password": "it_works_again"
}




###
# Get jwt-token
POST {{host}}auth/jwt/create/ HTTP/1.1
content-type: application/json

{
  "username": "max",
  "password": "auihhoue3p"
}

###
{
  "username": "max",
  "password": "auihhoue3p"
}
{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3NDA2NTcxOSwianRpIjoiY2U0YjI5ZWY4YTA0NDg3ZjljZjgzNzc3OGNjMWY5ZTQiLCJ1c2VyX2lkIjozfQ.XuacPA-IBYMyQ_uFvt27ViaXyrcBo6WNKldBY9oEpjs",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc0MDY1NzE5LCJqdGkiOiIwNjRiMjVjYmVhMjU0ODk0ODhjMjc5MGRlYzE5NDhlMyIsInVzZXJfaWQiOjN9.km0stUo6GBxpDxf4mi-1VWB4F2CQtyMVBvTWONkGtb4"
}

###
{
  "username": "maria",
  "password": "autnahunath"
}
{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3NDA2NTY5MCwianRpIjoiNmQzZWQ1YjJkMTg1NDBhN2JkOTM2YjNkNGRkOWQ2ZjIiLCJ1c2VyX2lkIjoyfQ.ZTlHI1GrfZcopEcu-6JkDmWc1KSCEXriQPw1vMk0DAI",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc0MDY1NjkwLCJqdGkiOiJjMWQ5NDIyZjk0YjE0NzE1OWM1MTY1NDg5MmFiOTU2YSIsInVzZXJfaWQiOjJ9.yNIiQ8oLwhFU9120GnKSwrFesz60w47vB-1fq7b48Qs"
}

###
{
  "username": "robert",
  "password": "t3DwwT#hnh8"
}
{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTY3NDA2NTY0NCwianRpIjoiMzM0NmZjM2FlZjMxNGM5ODhmMGI1NGRiNjA1MTk1MWYiLCJ1c2VyX2lkIjoxfQ.j_s3RM0Z6qOuSVah2OTLeSK3DGjLZ0o-cB0r9La-LHE",
  "access": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc0MDY1NjQ0LCJqdGkiOiIyNWI0NzVjN2IxMzY0N2E1YWQ5NjNhN2Y0ZTIyYjQzNSIsInVzZXJfaWQiOjF9.yXxnGbDbk-4l7Bk64eQqlX2bsOA2Ihe63Fl2xoqC63M"
}
###



###
POST {{ host }}api-token-auth/
content-type: application/json

{
  "username": "ignaz",
  "password": "123"
}

###